function createIntroduction() {
    // Create a new div element to hold the introduction content
    var divElement = document.createElement('div');
    
    // Set an ID attribute for the div element
    divElement.setAttribute('id', 'introDiv');
    
    // Create a close button to allow users to hide the introduction section
    var closeButton = document.createElement('span');
    closeButton.innerHTML = 'x'; // Display 'x' as the close button
    // Style the close button for visual appeal
    closeButton.style.cursor = 'pointer';
    closeButton.style.float = 'right';
    closeButton.style.color = '#ff0000'; // Red color for demonstration
    closeButton.style.fontSize = '24px';
    closeButton.style.margin = '-50px -5px 0 0'; // Adjust margins for positioning
    
    // Add a click event listener to the close button to hide the introduction section
    closeButton.addEventListener('click', function() {
        divElement.style.display = 'none';
        var introSection = document.getElementById('introductiontext');
        introSection.style.display = 'none';
    });
    
    // Create a title for the introduction section
    var titleElement = document.createElement('h2');
    titleElement.innerHTML = 'IMSHelferchen Einführung';
    
    // Create a text node containing the introduction text
    var introText = document.createTextNode('Die Bibliothek bietet eine Fülle von Links zu Unterrichtsmaterialien, damit du schnell auf relevante Seiten zugreifen kannst. Unser Notenrechner ermöglicht es dir, deine Fortschritte im Blick zu behalten und dich auf das Wesentliche zu konzentrieren. Der Stundenplanabruf sorgt dafür, dass du immer den Überblick behältst und pünktlich zu deinen Informatikstunden erscheinst. Mit dem IMSHelferchen wird das Navigieren durch den Unterricht zum Kinderspiel, damit du dich voll und ganz auf das Erlernen von Programmiersprachen und informatischen Konzepten konzentrieren kannst.');
    
    // Append the title, close button, and introduction text to the div element
    divElement.appendChild(titleElement);
    divElement.appendChild(closeButton);
    divElement.appendChild(introText);
    
    // Get the introductiontext section element from the HTML by its ID
    var introSection = document.getElementById('introductiontext');
    
    // Append the div containing the introduction to the introductiontext section
    introSection.appendChild(divElement);
}

// Call the createIntroduction function when the window has finished loading
window.onload = createIntroduction;
//comments are generated by ChatGPT