document.addEventListener("DOMContentLoaded", function () {
  
  // Function to show only the selected section and hide others.
  function showOnlySelectedSection(selectedSection) {
    // List of all sections to manage visibility.
    const sections = [librarySection, gradeCalculatorSection, timetableSection];
    
    // Loop through each section to set its display property.
    sections.forEach(section => {
      section.style.display = (section === selectedSection) ? "block" : "none";
    });
  }

  // Get references to the HTML sections by their IDs.
  const librarySection = document.getElementById("library");
  const gradeCalculatorSection = document.getElementById("gradeCalculator");
  const timetableSection = document.getElementById("timetable");

  // Initially hide all sections.
  librarySection.style.display = "none";
  gradeCalculatorSection.style.display = "none";
  timetableSection.style.display = "none";

  // Function to handle the click event on a navigation link.
  function handleNavLinkClick(event, section) {
    event.preventDefault(); // Prevent the default action of the link.
    showOnlySelectedSection(section); // Show only the selected section.
  }

  // Add click event listeners to the navigation links for each section.
  document.getElementById("library-link").addEventListener("click", (event) => {
    handleNavLinkClick(event, librarySection);
  });

  document.getElementById("gradeCalculator-link").addEventListener("click", (event) => {
    handleNavLinkClick(event, gradeCalculatorSection);
  });

  document.getElementById("timetable-link").addEventListener("click", (event) => {
    handleNavLinkClick(event, timetableSection);
  });
});
//comments are generated by ChatGPT